### ISSUE TITLE
Estudo da Viabilidade

### ISSUE THREAD

**Issue by BiancaFSilva** [BiancaFSilva/Dionysius#1]
# Dionysius: Catálogo de Vinhos & Espumantes
Software desenvolvido como um projeto colaborativo entre as disciplinas Engenharia de Software I e Sistemas de Informação

### Equipe
- [Bianca Letícia Floriano da Silva](https://github.com/BiancaFSilva)
- [Gabrielle Ramos Barreto](https://github.com/GabsRB)

### Objetivo
O Software Dionysius é um e-commerce desenvolvido a partir de uma [API de Listagem de Vinhos](https://www.globalwinescore.com/ranking/?idx=Wine) que visa facilitar o acesso a informações e produtos relacionados ao vinho e à organização de eventos de degustação para associados.
- **Público-alvo:** interessados em vinho, possiveis compradores e degustadores

### Descrição do Software
A seguir serão listadas algumas páginas da aplicação com seus componentes e funcionalidades iniciais:
- **Landing Page:** contendo uma apresentação do projeto (catálogo e loja), alguns produtos demonstrativos, newsletter (opção de disponibilizar um e-mail para receber informações exclusivas), galeria de vinhos simples, informações de contato e possibilidade de login para associados e membros administrativos
- **Login:** formulário de login com duas possibilidades (usuário administrativo e cliente previamente associado)
- **Produto:** página de vendas, contendo imagens e informações do vinho (especificação do tipo, cor, ano, região/país de origem, avaliações e valor)
- **Associados:** através do login de clientes associados, será desbloqueada uma página com informações exclusivas como descontos, informações completas sobre safras, harmonização com alimentos, contato com fornecedores, vinhedos e eventos de degustação
- **Dashboard:** página de acesso restrito a usuários de nível administrativo, consiste em um painel de controle das informações de estoque, vendas, fornecedores, cadastro e gerenciamento de associados e compradores integrado a um banco de dados relacional próprio.

**Comment by GabsRB** [comment]
aaaaaaaa

**Comment by BiancaFSilva** [comment]
# Elicitação de Requisitos
![image](https://user-images.githubusercontent.com/60801421/187280302-0e9f05ee-ec7e-4c96-8101-561d0759bca5.png)

[Levantamento de Requisitos.docx](https://github.com/BiancaFSilva/Dionysius/files/9447355/Diagrama.de.Contexto.docx)

**Comment by BiancaFSilva** [comment]
# Diagrama de Contexto

![Image](https://user-images.githubusercontent.com/60801421/202916022-49fd1e37-20b3-4303-80d8-7cb59ec6e21a.jpg)
